#!/bin/bash

#DOCUMENTATION
#PR _branch_ _message_

git checkout $1
git add .
git commit -m "$2"
git push
echo -e "\nChanges pushed\n"

url=`hub pull-request -m "$2"`
echo -e "\nPull request created\n"

git checkout master
hub merge $url
git push
echo -e "\nPull request merged and pushed\n"

git checkout $1
git pull origin master
git push
