#!/bin/bash

#DOCUMENTATION
#PR _branch_ _message_

git checkout $1
git add .
git commit -m "$2"
git push
echo "Changes pushed\n"

url=`echo hub pull-request -m "$2"`
echo "Pull request created\n"

git checkout master
hub merge $url 
git push
echo "Pull request merged and pushed\n"

git checkout $1
